baseurl = "https://aviariesdepot.com.au"
languageCode = "en-au"
title = "Aviaries Depot"
theme = "hugo-creative-theme"
googleAnalytics = "UA-111712204-3"
paginate = 12

[taxonomies]
  category = "categories"
  tag = "tags"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Aviaries Depot"
	description = "Keeping your furry friends entertained and Active while preserving your beloved furniture from their sharp claws, Aviaries Depot for scratch problems"
	copyright = "Copyright 2007-{year} Example LLC. All rights reserved."

	# The path must be relative to the static folder
	favicon = "favicon.png"


	# Navigation
	[params.navigation]
		brand = "Aviaries Depot"
		brand_logo = "img/logo-40h.png"

		[params.navigation.links]
			about     			= "About"
			testimonials    	= "Testimonials"
			services  			= "Services"
			portfolio 			= "More Info"
			contact   			= "Contact"
			blog				= "News"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = ""
		subtitle   = ""
		buttonText = ""


	# About section
	[params.about]
		headline    = "Bird Cages suitable for your need and preferences"
		description = "We provide many types of cages for your bird which is safe, durable, and more importantly spacious to allow them to fly around freely."
		buttonText  = "Products!"
		desc_old    = "[Lorem](//google.com) ipsum dolor sit amet, consectetur adipisicing elit. Praesentium similique eos eligendi error veritatis harum, sed aliquid totam, quam minus neque enim est architecto, ad. Maiores, aliquid, vitae!"

	# Footer
	[params.footer]
		headline    = ""
		description = "Looking for secure cages for your feathered friends but don't want them to feel trapped and cramped in a small space?  Contact us for a solution that is suitable for your needs."

	# Testimonials
	[params.testimonials]
		headline    = "What our customers are saying..."

        [[params.testimonials.list]]
			description		= "Got my first Bird Cage today ! Great product with great price and great customer service. Highly recommended store !"
			name			= "Ishida T."

        [[params.testimonials.list]]
			description		= " My Shopping experience at [aviariesdepot.com](aviariesdepot.com) has been phenomenal. It was easy to locate the products i was looking for and the price match ensured that i did not get rip off anywhere online."
			name			= "Jenny L."

        [[params.testimonials.list]]
			description		= "I found the most suitable **Bird Cage** ! staff were friendly and i really appreciated the free gift as one of the first few new customers. Highly recommended store."
			name			= "John P."

	# Service section
	[params.services]
		headline = "Our Promise"

        [[params.services.list]]
            icon = "fa-truck"
            title = "Quick & Easy Shipping"
            description_x = "Easy door to door deliveries."

        [[params.services.list]]
			icon = "fa-money"
			title = "Price Match Guarantee"
			description_x = "Price match guarantee on our instore products!"

		[[params.services.list]]
            icon = "fa-newspaper-o"
            title = "Hassel Free Returns"
            description_x = "Let us deal with it for you."

        [[params.services.list]]
            icon = "fa-phone"
            title = "Dedicated support"
            description_x = "Talk with our operators!"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	# [params.aside]
	# 	headline = "Expert Advice"

	# 	[params.aside.button]
	# 		text = "Download now"
	# 		link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	# [params.contact]
	# 	headline = "Let's Get In Touch!"
	# 	description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
	# 	phone = "123-456-6789"
	# 	email = "feedback@startbootstrap.com"

	# Blog
	[params.blog]
		path = "/news"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
